[package]
name = "comprustion"
version = "0.1.0"
authors = ["Alex Vig <jalexvig@gmail.com>"]
description = "Implementation of various compression algorithms."
license = "MIT"

[dependencies]
bit-vec = "0.4.4"
